language: node_js
node_js:
- 0.10

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
#    - BROWSER=firefox BVER=stable
#    - BROWSER=firefox BVER=beta
#    - BROWSER=firefox BVER=aurora

before_install:
  - mkdir -p .travis
  - curl -s https://codeload.github.com/rtc-io/webrtc-testing-on-travis/tar.gz/master | tar -xz --strip-components=1 --directory .travis
  - ./.travis/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io
